### ISSUE TITLE
Saving in ba_outro in Blue Shift crashes the game on Linux

### ISSUE THREAD

**Issue by chinese-soup** [YaLTeR/BunnymodXT#152]
Low priority

```
Protocol version 48
Exe version 1.1.2.2/Stdio (valve)
Exe build: 19:53:35 Aug  3 2020 (8684)
```

Note: This is incorrect, I am actually running https://github.com/YaLTeR/BunnymodXT/releases/tag/jan-11-2021
```
Bunnymod XT version Oct  1 2020 11:26:15.
[DevMsg] BXT: Opened the message queue.
[DevMsg] SPTLib version 1.2.
```
And same thing happens in a build of the current master branch

```c++
Core was generated by `./hl_linux -steam -game bshift'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x8dadf940 in EHANDLE::Get (this=0x9f79fdc) at ../blueshift/dlls/cbase.cpp:446
446	../blueshift/dlls/cbase.cpp: No such file or directory.
[Current thread is 1 (Thread 0xe8d81780 (LWP 621418))]
(gdb) bt
#0  0x8dadf940 in EHANDLE::Get (this=0x9f79fdc) at ../blueshift/dlls/cbase.cpp:446
#1  EHANDLE::operator CBaseEntity* (this=0x9f79fdc) at ../blueshift/dlls/cbase.cpp:465
#2  0x8db83268 in CSave::WriteFields (this=0xfff7b52c, pname=0x8dbb87b7 "CTriggerPlayerFreeze", pBaseData=0x9f79f70, pFields=0x8dbede40 <CTriggerPlayerFreeze::m_SaveData>, 
    fieldCount=1) at ../blueshift/dlls/util.cpp:2106
#3  0x8db735dc in CTriggerPlayerFreeze::Save (save=..., this=0x9f79f70) at ../blueshift/dlls/triggers.cpp:2460
#4  CTriggerPlayerFreeze::Save (this=0x9f79f70, save=...) at ../blueshift/dlls/triggers.cpp:2456
#5  0x8dade8ac in DispatchSave (pent=0xbb23302c, pSaveData=0x8d67e010) at ../blueshift/dlls/cbase.cpp:278
#6  0xe769477f in SaveGamestate () at ../engine/host_cmd.c:2579
#7  0xe7695d3d in SaveGameSlot (pSaveName=0xbaf13128 "quick.sav", pSaveComment=0xfff7bc80 "#BA_OUTRO", ' ' <repeats 56 times>, "00:58") at ../engine/host_cmd.c:2072
#8  0xe7696795 in Host_Savegame_f () at ../engine/host_cmd.c:2208
#9  Host_Savegame_f () at ../engine/host_cmd.c:2168
#10 0xe76768de in Cmd_ExecuteStringWithPrivilegeCheck (text=0xfff7bd90 "save quick", bIsPrivileged=<optimized out>, src=<optimized out>) at ../engine/cmd.c:1257
#11 0xe7676b38 in Cmd_ExecuteStringWithPrivilegeCheck (bIsPrivileged=true, src=src_command, text=0xfff7bd90 "save quick") at ../engine/cmd.c:1216
#12 Cbuf_ExecuteCommandsFromBuffer (buf=0xe7edfb50 <cmd_text>, bIsPrivileged=true, nCmdsToExecute=-1) at ../engine/cmd.c:245
#13 0xe7676b71 in Cbuf_ExecuteFromBuffer (bIsPrivileged=true, buf=0xe7edfb50 <cmd_text>) at ../engine/cmd.c:259
#14 Cbuf_Execute () at ../engine/cmd.c:269
#15 0xe9354da7 in HwDLL::HOOKED_Cbuf_Execute_Func() () from /home/unko/bxt/libBunnymodXT.so
#16 0xe9355dac in HwDLL::HOOKED_Cbuf_Execute() () from /home/unko/bxt/libBunnymodXT.so
#17 0xe9355dd4 in Cbuf_Execute () from /home/unko/bxt/libBunnymodXT.so
#18 0xe768e7a3 in _Host_Frame (time=4.82999985e-06) at ../engine/host.c:1410
#19 0xe768ec52 in Host_Frame (time=4.82999985e-06, iState=1, stateInfo=0xfff7c5fc) at ../engine/host.c:1548
#20 0xe76bbb04 in CEngine::Frame (this=0xe78d5aa0 <g_Engine>) at ../engine/sys_engine.cpp:245
#21 0xe76b958b in RunListenServer (instance=0x0, basedir=0x804b220 <szBaseDir> ".", cmdline=0x92f5e00 "./hl_linux -steam -game bshift", 
    postRestartCmdLineArgs=0x804d360 <main::szNewCommandParams> "", launcherFactory=0x8049350 <CreateInterfaceLocal(char const*, int*)>, filesystemFactory=
    0xe88f6d40 <CreateInterface(char const*, int*)>) at ../engine/sys_dll2.cpp:955
#22 0x08048d67 in main (argc=4, argv=0xfff7c844) at ../launcher/launcher.cpp:439
```

**Comment by hobokenn** [comment]
pretty sure this happens on windows too and is unrelated to bxt https://github.com/ValveSoftware/halflife/issues/1014

**Comment by chinese-soup** [comment]
> pretty sure this happens on windows too and is unrelated to bxt [ValveSoftware/halflife#1014](https://github.com/ValveSoftware/halflife/issues/1014)

My bad, thanks.
