### ISSUE TITLE
CMultiManager::ManagerUse hook crashes on Linux

### ISSUE THREAD

**Issue by YaLTeR** [YaLTeR/BunnymodXT#63]

**Comment by YaLTeR** [comment]
- Commenting out the hook fixes the crash.
- Commenting out the contents and leaving just the call back doesn't fix the crash.
- The calling convention and parameters do not seem to have changed.
- The original address BXT finds seems correct.
- The crash is in `CBaseEntity::Use` without the hook in the backtrace.

```
#0  0xa1a2f558 in CBaseEntity::Use (this=0xa648130, pActivator=0xa641870, pCaller=0xa641870, useType=USE_ON, value=0)
    at ../dlls/cbase.h:220
#1  0xa1ace542 in FireTargets (targetName=0xcfcc6c78 "entrymm", pActivator=0xa641870, pCaller=0xa641870, useType=USE_ON,
    value=0) at ../dlls/subs.cpp:207
#2  0xa1ace97a in CBaseDelay::SUB_UseTargets (this=0xa641870, pActivator=0xa641870, useType=USE_ON, value=0)
    at ../dlls/subs.cpp:282
#3  0xa1ad92ba in CAutoTrigger::Think (this=0xa641870) at ../dlls/triggers.cpp:180
#4  CAutoTrigger::Think (this=0xa641870) at ../dlls/triggers.cpp:176
#5  0xf5ff1636 in SV_RunThink (ent=0xcfa1c3dc) at ../engine/sv_phys.c:153
#6  SV_Physics_None (ent=0xcfa1c3dc) at ../engine/sv_phys.c:1392
#7  SV_Physics () at ../engine/sv_phys.c:2040
#8  0xf5fe9076 in SV_Frame () at ../engine/sv_main.c:9352
#9  0xf7c791d4 in HwDLL::HOOKED_SV_Frame_Func (this=this@entry=0xf7e37fe0 <HwDLL::GetInstance()::instance>)
    at ../BunnymodXT/modules/HwDLL.cpp:2956
#10 0xf7c7eba5 in HwDLL::HOOKED_SV_Frame () at ../BunnymodXT/modules/HwDLL.hpp:116
#11 0xf7c7ec37 in SV_Frame () at ../BunnymodXT/modules/HwDLL.cpp:72
#12 0xf5fa8676 in _Host_Frame (time=4.55300005e-06) at ../engine/host.c:1430
#13 0xf5fa8b02 in Host_Frame (time=4.55300005e-06, iState=1, stateInfo=0xffb3d24c) at ../engine/host.c:1548
#14 0xf5fd5944 in CEngine::Frame (this=0xf61ef380 <g_Engine>) at ../engine/sys_engine.cpp:245
#15 0xf5fd33d3 in RunListenServer (instance=0x0, basedir=0x804b220 <szBaseDir> ".",
    cmdline=0x9a54480 "./hl_linux -steam +sv_cheats 1 +host_framerate 0.010000001 +_bxt_min_frametime 0.01 +bxt_hud_origin 1 +bxt_hud_viewangles 1 +map c1a0", postRestartCmdLineArgs=0x804d360 <main::szNewCommandParams> "",
    launcherFactory=0x8049350 <CreateInterfaceLocal(char const*, int*)>,
    filesystemFactory=0xf7bb8d40 <CreateInterface(char const*, int*)>) at ../engine/sys_dll2.cpp:955
#16 0x08048d67 in main (argc=14, argv=0xffb3d484) at ../launcher/launcher.cpp:439
```
```
Dump of assembler code for function CBaseEntity::Use(CBaseEntity*, CBaseEntity*, USE_TYPE, float):
   0xa1a2f520 <+0>:	sub    esp,0x10
   0xa1a2f523 <+3>:	mov    edx,DWORD PTR [esp+0x14]
   0xa1a2f527 <+7>:	mov    DWORD PTR [esp],ebx
   0xa1a2f52a <+10>:	mov    ecx,DWORD PTR [esp+0x18]
   0xa1a2f52e <+14>:	mov    DWORD PTR [esp+0x4],esi
   0xa1a2f532 <+18>:	mov    ebx,DWORD PTR [esp+0x1c]
   0xa1a2f536 <+22>:	mov    DWORD PTR [esp+0x8],edi
   0xa1a2f53a <+26>:	mov    esi,DWORD PTR [esp+0x20]
   0xa1a2f53e <+30>:	mov    DWORD PTR [esp+0xc],ebp
   0xa1a2f542 <+34>:	mov    edi,DWORD PTR [esp+0x24]
   0xa1a2f546 <+38>:	mov    eax,DWORD PTR [edx+0x20]
   0xa1a2f549 <+41>:	test   eax,eax
   0xa1a2f54b <+43>:	je     0xa1a2f588 <CBaseEntity::Use(CBaseEntity*, CBaseEntity*, USE_TYPE, float)+104>
   0xa1a2f54d <+45>:	mov    ebp,DWORD PTR [edx+0x24]
   0xa1a2f550 <+48>:	add    edx,ebp
   0xa1a2f552 <+50>:	test   al,0x1
   0xa1a2f554 <+52>:	je     0xa1a2f55c <CBaseEntity::Use(CBaseEntity*, CBaseEntity*, USE_TYPE, float)+60>
   0xa1a2f556 <+54>:	mov    ebp,DWORD PTR [edx]
=> 0xa1a2f558 <+56>:	mov    eax,DWORD PTR [ebp+eax*1-0x1]
   0xa1a2f55c <+60>:	mov    DWORD PTR [esp+0x24],edi
   0xa1a2f560 <+64>:	mov    ebp,DWORD PTR [esp+0xc]
   0xa1a2f564 <+68>:	mov    DWORD PTR [esp+0x20],esi
   0xa1a2f568 <+72>:	mov    edi,DWORD PTR [esp+0x8]
   0xa1a2f56c <+76>:	mov    DWORD PTR [esp+0x1c],ebx
   0xa1a2f570 <+80>:	mov    esi,DWORD PTR [esp+0x4]
   0xa1a2f574 <+84>:	mov    DWORD PTR [esp+0x18],ecx
   0xa1a2f578 <+88>:	mov    ebx,DWORD PTR [esp]
   0xa1a2f57b <+91>:	mov    DWORD PTR [esp+0x14],edx
   0xa1a2f57f <+95>:	add    esp,0x10
   0xa1a2f582 <+98>:	jmp    eax
   0xa1a2f584 <+100>:	lea    esi,[esi+eiz*1+0x0]
   0xa1a2f588 <+104>:	mov    ebx,DWORD PTR [esp]
   0xa1a2f58b <+107>:	mov    esi,DWORD PTR [esp+0x4]
   0xa1a2f58f <+111>:	mov    edi,DWORD PTR [esp+0x8]
   0xa1a2f593 <+115>:	mov    ebp,DWORD PTR [esp+0xc]
   0xa1a2f597 <+119>:	add    esp,0x10
   0xa1a2f59a <+122>:	ret
```
```
eax            0xf7ca34fd          -137743107
ecx            0xa641870           174332016
edx            0xa648130           174358832
ebx            0xa641870           174332016
esp            0xffb3cfbc          0xffb3cfbc
ebp            0xa1b1d8a8          0xa1b1d8a8 <vtable for CMultiManager+8>
esi            0x1                 1
edi            0x0                 0
eip            0xa1a2f558          0xa1a2f558 <CBaseEntity::Use(CBaseEntity*, CBaseEntity*, USE_TYPE, float)+56>
eflags         0x10202             [ IF RF ]
cs             0x23                35
ss             0x2b                43
ds             0x2b                43
es             0x2b                43
fs             0x0                 0
gs             0x63                99
```
The eax value seems sketchy but idk.
